### ISSUE TITLE
opencv-python armv6l

### ISSUE THREAD

**Issue by mbalamat** [piwheels/packages#43]
Package name: opencv-python
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/opencv-python/
Link to piwheels page: https://www.piwheels.org/project/opencv-python/
Version: Tested 3.4.4.19, 3.4.3.18
Python version: 3.5.3
More information:
OS: Debian Stretch
It works on a pi3, it throws illegal instruction error on pi Zero.

```
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Illegal instruction (core dumped)
```

**Comment by bennuttall** [comment]
You can't use the armv7 wheel on a Pi 1/Zero. Most packages are compatible with both, but opencv ones are built separately with optimisations for Pi 3.

If you want to be able to use the same card on both models, uninstall it and reinstall using a Pi 1/Zero:

```
sudo pip3 uninstall opencv-python -y
sudo pip3 install opencv-python
```

**Comment by mbalamat** [comment]
@bennuttall Sorry I wasn't clear enough I am not using the same card, I got 2 devices (pi3, piZero) and on the pi Zero it correctly downloaded the armv6l wheel and it threw the error above. Pretty sure it was working a month ago.

**Comment by mbalamat** [comment]
```
root@442fe0a:/usr/src/app# pip3 uninstall opencv-python -y
Uninstalling opencv-python-3.4.4.19:
  Successfully uninstalled opencv-python-3.4.4.19
root@442fe0a:/usr/src/app# pip3 install opencv-python --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python
  Downloading https://www.piwheels.org/simple/opencv-python/opencv_python-3.4.4.19-cp35-cp35m-linux_armv6l.whl (7.2MB)
     |████████████████████████████████| 7.2MB 739kB/s 
Requirement already satisfied: numpy>=1.12.1 in /usr/local/lib/python3.5/dist-packages (from opencv-python) (1.16.4)
Installing collected packages: opencv-python
Successfully installed opencv-python-3.4.4.19
root@442fe0a:/usr/src/app# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Illegal instruction (core dumped)
```

**Comment by bennuttall** [comment]
Ok could be something else, we're looking into it.

**Comment by mbalamat** [comment]
@bennuttall any updates?

**Comment by idoodler** [comment]
Any updates?

**Comment by idoodler** [comment]
@bennuttall Any updates?

**Comment by chrisys** [comment]
@bennuttall any updates on resolving the issue with this package for the Pi Zero? We have had a few people reporting it recently.

**Comment by Arconapalus** [comment]
Hello all, I recently dive into a balena cloud projects and upon build the docker image for the raspberry pi zero /w. Failed to compile for the device. 
Upon with support of this, I was directed here. 
I know there's a issue with opencv-python but will this be remedy any time soon?

**Comment by bennuttall** [comment]
Thanks everyone for your patience. We have now imported new opencv wheels and I believe this issue should now be resolved. Please test and let us know!

**Comment by idoodler** [comment]
@mbalamat I just tried it again, but I have still the same issue. I guess I have to bump up some version, but I honestly don't know which one.

**Comment by Arconapalus** [comment]
Thank you, Will test in the next couple days

**Comment by Arconapalus** [comment]
Thank you, I was able to clone latest git repo and balena push was successful. 
However, the video is still and shows duplicate screen when I access the public url. 
Would using the turn server help this or not? 
thank you again for all who has worked on this

**Comment by idoodler** [comment]
I am able to view the live camera stream, however with a major latency.
